name: Deploy GitHub Pages (subfolder)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'false'   # avoid accidental submodule fetches
          fetch-depth: 0

      - name: Upload Pages artifact (electionstowatch/)
        uses: actions/upload-pages-artifact@v3
        with:
          path: electionstowatch   # <-- this becomes the deployed site ROOT

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
